@startuml
'Create graph:
'set path=%path%;<java location>;<graphviz location>
'java -jar <plantuml.jar location>/plantuml.jar graph.puml
digraph Foo {
0 [color="green", level=1, pos=1, type=mainline];
1 [color="green", level=2, pos=2, type=mainline];
2 [color="green", level=2, pos=3, type=mainline];
10 [allowed_dirs="west north south", color="gray", guards=1, label="10 g1", pos=1, room_style=3, type=branch];
11 [allowed_dirs="down up north south east", color="gray", pos=1, room_style=3, type=branch];
12 [allowed_dirs="west down north south east", color="gray", pos=1, room_style=3, type=branch];
13 [allowed_dirs="north south east", color="gray", pos=1, room_style=3, type=branch];
14 [allowed_dirs="west down up north south", color="gray", pos=1, room_style=3, type=branch];
15 [allowed_dirs="west up north south east", color="gray", key_defender=1, label="15 key1", pos=1, room_style=3, type=branch];
3 [color="green", level=2, pos=4, type=mainline];
16 [allowed_dirs="west up south east", color="gray", guards=1, label="16 g1", pos=2, room_style=5, type=branch];
17 [allowed_dirs="west down up north south", color="gray", pos=2, room_style=5, type=branch];
18 [allowed_dirs="west down up north east", color="gray", pos=2, room_style=5, type=branch];
19 [allowed_dirs="down up south", color="gray", key_defender=2, label="19 key2", pos=2, room_style=5, type=branch];
20 [allowed_dirs="down north south east", color="gray", pos=2, room_style=5, type=branch];
21 [allowed_dirs="west down up north east", color="gray", pos=2, room_style=5, type=branch];
4 [color="green", level=2, pos=5, type=mainline];
22 [allowed_dirs="west up east", color="gray", guards=1, label="22 g1", pos=3, room_style=5, type=branch];
23 [allowed_dirs="west up south east", color="gray", pos=3, room_style=5, type=branch];
24 [allowed_dirs="west down north south", color="gray", pos=3, room_style=5, type=branch];
25 [allowed_dirs="down north east", color="gray", key_defender=2, label="25 key2", pos=3, room_style=5, type=branch];
26 [allowed_dirs="west down up east", color="gray", pos=3, room_style=5, type=branch];
5 [color="green", level=3, pos=6, type=mainline];
27 [allowed_dirs="west down up east", color="gray", guards=1, label="27 g1", pos=4, room_style=1, type=branch];
28 [allowed_dirs="west up", color="gray", pos=4, room_style=1, type=branch];
29 [allowed_dirs="west north south east", color="gray", pos=4, room_style=1, type=branch];
30 [allowed_dirs="down north south", color="gray", key_defender=2, label="30 key2", pos=4, room_style=1, type=branch];
31 [allowed_dirs="down up east", color="gray", pos=4, room_style=1, type=branch];
6 [color="green", level=3, pos=7, type=mainline];
32 [allowed_dirs="west down up north", color="gray", guards=1, label="32 g1", pos=5, room_style=1, type=branch];
33 [allowed_dirs="west east", color="gray", pos=5, room_style=1, type=branch];
34 [allowed_dirs="west down up south", color="gray", key_defender=3, label="34 key3", pos=5, room_style=1, type=branch];
35 [allowed_dirs="down south east", color="gray", pos=5, room_style=1, type=branch];
36 [allowed_dirs="up north east", color="gray", pos=5, room_style=1, type=branch];
7 [color="green", level=3, pos=8, type=mainline];
37 [allowed_dirs="down up north south east", color="gray", guards=2, label="37 g2", pos=6, room_style=3, type=branch];
38 [allowed_dirs="west down up", color="gray", pos=6, room_style=3, type=branch];
39 [allowed_dirs="west down up east", color="gray", pos=6, room_style=3, type=branch];
40 [allowed_dirs="west down south east", color="gray", key_defender=3, label="40 key3", pos=6, room_style=3, type=branch];
41 [allowed_dirs="west down up north east", color="gray", pos=6, room_style=3, type=branch];
42 [allowed_dirs="west up north south east", color="gray", pos=6, room_style=3, type=branch];
8 [color="green", level=4, pos=9, type=mainline];
43 [allowed_dirs="west down up south east", color="gray", guards=2, label="43 g2", pos=7, room_style=5, type=branch];
44 [allowed_dirs="west up north", color="gray", pos=7, room_style=5, type=branch];
45 [allowed_dirs="down north south east", color="gray", key_defender=4, label="45 key4", pos=7, room_style=5, type=branch];
46 [allowed_dirs="down up south east", color="gray", pos=7, room_style=5, type=branch];
47 [allowed_dirs="west down up north south", color="gray", pos=7, room_style=5, type=branch];
48 [allowed_dirs="west down up north east", color="gray", pos=7, room_style=5, type=branch];
9 [color="green", level=4, pos=10, type=mainline];
49 [allowed_dirs="west up north", color="gray", guards=2, label="49 g2", pos=8, room_style=5, type=branch];
50 [allowed_dirs="down north south east", color="gray", key_defender=4, label="50 key4", pos=8, room_style=5, type=branch];
51 [allowed_dirs="up south east", color="gray", pos=8, room_style=5, type=branch];
52 [allowed_dirs="west down up north south", color="gray", pos=8, room_style=5, type=branch];
53 [allowed_dirs="west down north south east", color="gray", pos=8, room_style=5, type=branch];
0 -> 1  [direction=north, label=n];
1 -> 0  [direction=south, label=s];
1 -> 2  [direction=east, label=e];
1 -> 10  [direction=nw, label=nw];
2 -> 1  [direction=west, label=w];
2 -> 3  [direction=north, label=n];
2 -> 16  [direction=nw, label=nw];
10 -> 11  [direction=east, label=e];
10 -> 12  [direction=down, label=d];
10 -> 13  [direction=up, label=u];
10 -> 1  [direction=se, label=se];
11 -> 10  [direction=west, label=w];
12 -> 10  [direction=up, label=u];
13 -> 10  [direction=down, label=d];
13 -> 14  [direction=west, label=w];
13 -> 15  [direction=up, label=u];
14 -> 13  [direction=east, label=e];
15 -> 13  [direction=down, label=d];
3 -> 2  [direction=south, label=s];
3 -> 4  [direction=east, label=e];
3 -> 22  [direction=nw, label=nw];
16 -> 20  [direction=down, label=d];
16 -> 21  [direction=north, label=n];
16 -> 2  [direction=se, label=se];
17 -> 19  [direction=east, label=e];
18 -> 19  [direction=south, label=s];
19 -> 17  [direction=west, label=w];
19 -> 18  [direction=north, label=n];
19 -> 20  [direction=east, label=e];
20 -> 16  [direction=up, label=u];
20 -> 19  [direction=west, label=w];
21 -> 16  [direction=south, label=s];
4 -> 3  [direction=west, label=w];
4 -> 5  [direction=north, label=n];
4 -> 27  [direction=nw, label=nw];
22 -> 23  [direction=south, label=s];
22 -> 25  [direction=down, label=d];
22 -> 26  [direction=north, label=n];
22 -> 3  [direction=se, label=se];
23 -> 22  [direction=north, label=n];
23 -> 24  [direction=down, label=d];
24 -> 23  [direction=up, label=u];
24 -> 25  [direction=east, label=e];
25 -> 22  [direction=up, label=u];
25 -> 24  [direction=west, label=w];
25 -> 26  [direction=south, label=s];
26 -> 22  [direction=south, label=s];
26 -> 25  [direction=north, label=n];
5 -> 4  [direction=south, label=s];
5 -> 6  [direction=east, label=e];
5 -> 32  [direction=nw, label=nw];
27 -> 28  [direction=south, label=s];
27 -> 31  [direction=north, label=n];
27 -> 4  [direction=se, label=se];
28 -> 27  [direction=north, label=n];
28 -> 29  [direction=down, label=d];
28 -> 30  [direction=east, label=e];
28 -> 31  [direction=south, label=s];
29 -> 28  [direction=up, label=u];
29 -> 30  [direction=down, label=d];
30 -> 28  [direction=west, label=w];
30 -> 29  [direction=up, label=u];
30 -> 31  [direction=east, label=e];
31 -> 27  [direction=south, label=s];
31 -> 28  [direction=north, label=n];
31 -> 30  [direction=west, label=w];
6 -> 5  [direction=west, label=w];
6 -> 7  [direction=east, label=e];
6 -> 37  [direction=nw, label=nw];
32 -> 33  [direction=south, label=s];
32 -> 36  [direction=east, label=e];
32 -> 5  [direction=se, label=se];
33 -> 32  [direction=north, label=n];
33 -> 34  [direction=south, label=s];
33 -> 35  [direction=down, label=d];
33 -> 36  [direction=up, label=u];
34 -> 33  [direction=north, label=n];
34 -> 35  [direction=east, label=e];
35 -> 33  [direction=up, label=u];
35 -> 34  [direction=west, label=w];
35 -> 36  [direction=north, label=n];
36 -> 32  [direction=west, label=w];
36 -> 33  [direction=down, label=d];
36 -> 35  [direction=south, label=s];
7 -> 6  [direction=west, label=w];
7 -> 8  [direction=north, label=n];
7 -> 43  [direction=nw, label=nw];
37 -> 38  [direction=west, label=w];
37 -> 6  [direction=se, label=se];
38 -> 37  [direction=east, label=e];
38 -> 39  [direction=north, label=n];
38 -> 40  [direction=south, label=s];
39 -> 38  [direction=south, label=s];
39 -> 41  [direction=north, label=n];
40 -> 38  [direction=north, label=n];
40 -> 42  [direction=up, label=u];
41 -> 39  [direction=south, label=s];
42 -> 40  [direction=down, label=d];
8 -> 7  [direction=south, label=s];
8 -> 9  [direction=east, label=e];
8 -> 49  [direction=nw, label=nw];
43 -> 44  [direction=north, label=n];
43 -> 7  [direction=se, label=se];
44 -> 43  [direction=south, label=s];
44 -> 45  [direction=down, label=d];
44 -> 46  [direction=east, label=e];
45 -> 44  [direction=up, label=u];
45 -> 47  [direction=west, label=w];
46 -> 44  [direction=west, label=w];
46 -> 48  [direction=north, label=n];
47 -> 45  [direction=east, label=e];
48 -> 46  [direction=south, label=s];
9 -> 8  [direction=west, label=w];
49 -> 50  [direction=east, label=e];
49 -> 51  [direction=south, label=s];
49 -> 53  [direction=down, label=d];
49 -> 8  [direction=se, label=se];
50 -> 49  [direction=west, label=w];
50 -> 51  [direction=up, label=u];
51 -> 49  [direction=north, label=n];
51 -> 50  [direction=down, label=d];
51 -> 52  [direction=west, label=w];
52 -> 51  [direction=east, label=e];
53 -> 49  [direction=up, label=u];
}
@enduml